### ISSUE TITLE
main.py does not support --dataset argument as stated on readme.md

### ISSUE THREAD

**Issue by gonzalorodrigo** [NERSC/cori-tf-distributed-examples#3]
--logdir is not implemented in the argument parser of main.py
If it is a relevant functionality maybe it should be added. Else, it should be removed from readme.md

**Comment by eracah** [comment]
@gonzalorodrigo 
fixed in 4ef89229e1e667edd6381e41083f0096d598ad18 and b1a3dae2e8ba353daaeb54df45233823d5532911
